### ISSUE TITLE
Multi module build

### ISSUE THREAD

**Issue by Tijs-2** [dinject/dinject-controller#35] opened 2020-07-30 20:06 UTC
Hi Rob,

Not to reopen the other ticket I use a new one. 

But my idea of using the ${revision} seems to work ok, but not with the flatten plugin. There a few bugs which makes it very difficult for me to use it. There are already tickets for it but I think the library is to big and does to much for what I want and that is rewrite the ${revision} to a version.

Now I found https://github.com/jcgay/unique-revision-maven-filtering which does just that, but it also had two issues, not updating the ${revision} on dependencies and removing the relativePath before posting.

I created a pull request there but if you are interested this is the branch I updated and am using:
https://github.com/Tijs-2/unique-revision-maven-filtering/tree/revision_for_dependencies

Not sure if you are still interested in this but I thought I send an update.
Tijs

**Comment by rbygrave** [comment] 2020-07-30 21:43
What is the issue with how it is setup at the moment.  It is working well for me building/testing/installing locally as well as releasing so I'm pretty happy with it.

The release plugin maintains the snapshot version numbers so I can't see what the issue is with the current build setup.

Cheers, Rob.

**Comment by Tijs-2** [comment] 2020-07-31 19:42
First of all there is no problem.
But I made a remark on the other issue which was incorrect and it seemed only fair to update that it is incorrect :)

Also I had an old version of your code and did not see the update you already made which does most of the stuff which I meant:
https://github.com/dinject/dinject-controller/commit/21a59d994881d0c5b6efda3e704543d4e0658268

So please ignore my comments!

**Comment by rbygrave** [comment] 2020-08-01 01:20
Ah cool.  The multi module setup before was not good so thanks for the input / thoughts.

It still isn't really ideal with respect to the "test modules" and maven release plugin but that should mostly only effect me when I release to central so I'm ok with it.

Cheers, Rob.

**Comment by rbygrave** [comment] 2020-08-26 12:28
Closing this now.

**Closed by rbygrave** 2020-08-26 12:28 UTC
